# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lex Chen\py_proj\text_watermarks\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choiceImageFilesBtn = QtWidgets.QPushButton(self.frame_3)
        self.choiceImageFilesBtn.setObjectName("choiceImageFilesBtn")
        self.horizontalLayout_3.addWidget(self.choiceImageFilesBtn)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.textWatermarkContentsLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.textWatermarkContentsLineEdit.setMinimumSize(QtCore.QSize(270, 0))
        self.textWatermarkContentsLineEdit.setObjectName("textWatermarkContentsLineEdit")
        self.horizontalLayout_3.addWidget(self.textWatermarkContentsLineEdit)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fontSizeSlideBar = QtWidgets.QSlider(self.frame_3)
        self.fontSizeSlideBar.setMinimum(32)
        self.fontSizeSlideBar.setSingleStep(5)
        self.fontSizeSlideBar.setProperty("value", 55)
        self.fontSizeSlideBar.setOrientation(QtCore.Qt.Horizontal)
        self.fontSizeSlideBar.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.fontSizeSlideBar.setTickInterval(5)
        self.fontSizeSlideBar.setObjectName("fontSizeSlideBar")
        self.horizontalLayout_3.addWidget(self.fontSizeSlideBar)
        self.fontSizeLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.fontSizeLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fontSizeLineEdit.setReadOnly(True)
        self.fontSizeLineEdit.setObjectName("fontSizeLineEdit")
        self.horizontalLayout_3.addWidget(self.fontSizeLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setMinimum(50)
        self.spinBox.setMaximum(300)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.defaultCurrentDateCb = QtWidgets.QCheckBox(self.frame_4)
        self.defaultCurrentDateCb.setObjectName("defaultCurrentDateCb")
        self.horizontalLayout_4.addWidget(self.defaultCurrentDateCb)
        self.realtimePreviewCb = QtWidgets.QCheckBox(self.frame_4)
        self.realtimePreviewCb.setObjectName("realtimePreviewCb")
        self.horizontalLayout_4.addWidget(self.realtimePreviewCb)
        self.previewBtn = QtWidgets.QPushButton(self.frame_4)
        self.previewBtn.setObjectName("previewBtn")
        self.horizontalLayout_4.addWidget(self.previewBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.radioBlack = QtWidgets.QRadioButton(self.frame_4)
        self.radioBlack.setObjectName("radioBlack")
        self.horizontalLayout_4.addWidget(self.radioBlack)
        self.radioGrey = QtWidgets.QRadioButton(self.frame_4)
        self.radioGrey.setObjectName("radioGrey")
        self.horizontalLayout_4.addWidget(self.radioGrey)
        self.radioWhite = QtWidgets.QRadioButton(self.frame_4)
        self.radioWhite.setObjectName("radioWhite")
        self.horizontalLayout_4.addWidget(self.radioWhite)
        self.addWatermarksBtn = QtWidgets.QPushButton(self.frame_4)
        self.addWatermarksBtn.setObjectName("addWatermarksBtn")
        self.horizontalLayout_4.addWidget(self.addWatermarksBtn)
        self.verticalLayout.addWidget(self.frame_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_6)
        self.graphicsView.setMinimumSize(QtCore.QSize(794, 585))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_6.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文字水印批量添加 Coding By LN3 IT"))
        self.choiceImageFilesBtn.setText(_translate("MainWindow", "选择文件"))
        self.label_2.setText(_translate("MainWindow", "文字内容:"))
        self.label_4.setText(_translate("MainWindow", "字体大小:"))
        self.label.setText(_translate("MainWindow", "透明度:"))
        self.label_3.setText(_translate("MainWindow", "日期:"))
        self.defaultCurrentDateCb.setText(_translate("MainWindow", "默认当前日期"))
        self.realtimePreviewCb.setText(_translate("MainWindow", "实时预览"))
        self.previewBtn.setText(_translate("MainWindow", "预览"))
        self.radioBlack.setText(_translate("MainWindow", "黑色"))
        self.radioGrey.setText(_translate("MainWindow", "灰色"))
        self.radioWhite.setText(_translate("MainWindow", "白色"))
        self.addWatermarksBtn.setText(_translate("MainWindow", "添加水印"))
        self.label_5.setText(_translate("MainWindow", "  注意:如图片像素较高,实时预览可能显示不完整,请手动点击预览按钮察看."))
