# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lex Chen\py_proj\text_watermarks\watermarkColorSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 437)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 20, 201, 407))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.blackFrame = QtWidgets.QFrame(self.frame)
        self.blackFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blackFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blackFrame.setObjectName("blackFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blackFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.blackFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.black = QtWidgets.QComboBox(self.blackFrame)
        self.black.setMinimumSize(QtCore.QSize(0, 20))
        self.black.setObjectName("black")
        self.black.addItem("")
        self.black.addItem("")
        self.black.addItem("")
        self.horizontalLayout.addWidget(self.black)
        self.verticalLayout_2.addWidget(self.blackFrame)
        self.grayFrame = QtWidgets.QFrame(self.frame)
        self.grayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grayFrame.setObjectName("grayFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.grayFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.grayFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gray = QtWidgets.QComboBox(self.grayFrame)
        self.gray.setMinimumSize(QtCore.QSize(0, 20))
        self.gray.setObjectName("gray")
        self.gray.addItem("")
        self.gray.addItem("")
        self.gray.addItem("")
        self.horizontalLayout_2.addWidget(self.gray)
        self.verticalLayout_2.addWidget(self.grayFrame)
        self.whiteFrame = QtWidgets.QFrame(self.frame)
        self.whiteFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whiteFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whiteFrame.setObjectName("whiteFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.whiteFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.whiteFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.white = QtWidgets.QComboBox(self.whiteFrame)
        self.white.setMinimumSize(QtCore.QSize(0, 20))
        self.white.setObjectName("white")
        self.white.addItem("")
        self.white.addItem("")
        self.white.addItem("")
        self.horizontalLayout_3.addWidget(self.white)
        self.verticalLayout_2.addWidget(self.whiteFrame)
        self.redFrame = QtWidgets.QFrame(self.frame)
        self.redFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.redFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.redFrame.setObjectName("redFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.redFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.redFrame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.red = QtWidgets.QComboBox(self.redFrame)
        self.red.setMinimumSize(QtCore.QSize(0, 20))
        self.red.setObjectName("red")
        self.red.addItem("")
        self.red.addItem("")
        self.red.addItem("")
        self.horizontalLayout_4.addWidget(self.red)
        self.verticalLayout_2.addWidget(self.redFrame)
        self.red2Frame = QtWidgets.QFrame(self.frame)
        self.red2Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.red2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.red2Frame.setObjectName("red2Frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.red2Frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.red2Frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.red2 = QtWidgets.QComboBox(self.red2Frame)
        self.red2.setMinimumSize(QtCore.QSize(0, 20))
        self.red2.setObjectName("red2")
        self.red2.addItem("")
        self.red2.addItem("")
        self.red2.addItem("")
        self.horizontalLayout_5.addWidget(self.red2)
        self.verticalLayout_2.addWidget(self.red2Frame)
        self.orangeFrame = QtWidgets.QFrame(self.frame)
        self.orangeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.orangeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.orangeFrame.setObjectName("orangeFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.orangeFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.orangeFrame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.orange = QtWidgets.QComboBox(self.orangeFrame)
        self.orange.setMinimumSize(QtCore.QSize(0, 20))
        self.orange.setObjectName("orange")
        self.orange.addItem("")
        self.orange.addItem("")
        self.orange.addItem("")
        self.horizontalLayout_6.addWidget(self.orange)
        self.verticalLayout_2.addWidget(self.orangeFrame)
        self.yellowFrame = QtWidgets.QFrame(self.frame)
        self.yellowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yellowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yellowFrame.setObjectName("yellowFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.yellowFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.yellowFrame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.yellow = QtWidgets.QComboBox(self.yellowFrame)
        self.yellow.setMinimumSize(QtCore.QSize(0, 20))
        self.yellow.setObjectName("yellow")
        self.yellow.addItem("")
        self.yellow.addItem("")
        self.yellow.addItem("")
        self.horizontalLayout_7.addWidget(self.yellow)
        self.verticalLayout_2.addWidget(self.yellowFrame)
        self.greenFrame = QtWidgets.QFrame(self.frame)
        self.greenFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.greenFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.greenFrame.setObjectName("greenFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.greenFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.greenFrame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.green = QtWidgets.QComboBox(self.greenFrame)
        self.green.setMinimumSize(QtCore.QSize(0, 20))
        self.green.setObjectName("green")
        self.green.addItem("")
        self.green.addItem("")
        self.green.addItem("")
        self.horizontalLayout_8.addWidget(self.green)
        self.verticalLayout_2.addWidget(self.greenFrame)
        self.cyanFrame = QtWidgets.QFrame(self.frame)
        self.cyanFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cyanFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cyanFrame.setObjectName("cyanFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.cyanFrame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.cyanFrame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.cyan = QtWidgets.QComboBox(self.cyanFrame)
        self.cyan.setMinimumSize(QtCore.QSize(0, 20))
        self.cyan.setObjectName("cyan")
        self.cyan.addItem("")
        self.cyan.addItem("")
        self.cyan.addItem("")
        self.horizontalLayout_9.addWidget(self.cyan)
        self.verticalLayout_2.addWidget(self.cyanFrame)
        self.blueFrame = QtWidgets.QFrame(self.frame)
        self.blueFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blueFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blueFrame.setObjectName("blueFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.blueFrame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.blueFrame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.blue = QtWidgets.QComboBox(self.blueFrame)
        self.blue.setMinimumSize(QtCore.QSize(0, 20))
        self.blue.setObjectName("blue")
        self.blue.addItem("")
        self.blue.addItem("")
        self.blue.addItem("")
        self.horizontalLayout_10.addWidget(self.blue)
        self.verticalLayout_2.addWidget(self.blueFrame)
        self.purpleFrame = QtWidgets.QFrame(self.frame)
        self.purpleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.purpleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.purpleFrame.setObjectName("purpleFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.purpleFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.purpleFrame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.purple = QtWidgets.QComboBox(self.purpleFrame)
        self.purple.setMinimumSize(QtCore.QSize(0, 20))
        self.purple.setObjectName("purple")
        self.purple.addItem("")
        self.purple.addItem("")
        self.purple.addItem("")
        self.horizontalLayout_11.addWidget(self.purple)
        self.verticalLayout_2.addWidget(self.purpleFrame)
        self.saveSettingBtn = QtWidgets.QPushButton(Dialog)
        self.saveSettingBtn.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.saveSettingBtn.setObjectName("saveSettingBtn")
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "背景色水印颜色设置"))
        self.label.setText(_translate("Dialog", "背景色:黑色"))
        self.black.setItemText(0, _translate("Dialog", "黑色"))
        self.black.setItemText(1, _translate("Dialog", "灰色"))
        self.black.setItemText(2, _translate("Dialog", "白色"))
        self.label_2.setText(_translate("Dialog", "背景色:灰色"))
        self.gray.setItemText(0, _translate("Dialog", "黑色"))
        self.gray.setItemText(1, _translate("Dialog", "灰色"))
        self.gray.setItemText(2, _translate("Dialog", "白色"))
        self.label_3.setText(_translate("Dialog", "背景色:白色"))
        self.white.setItemText(0, _translate("Dialog", "黑色"))
        self.white.setItemText(1, _translate("Dialog", "灰色"))
        self.white.setItemText(2, _translate("Dialog", "白色"))
        self.label_4.setText(_translate("Dialog", "背景色:红色"))
        self.red.setItemText(0, _translate("Dialog", "黑色"))
        self.red.setItemText(1, _translate("Dialog", "灰色"))
        self.red.setItemText(2, _translate("Dialog", "白色"))
        self.label_5.setText(_translate("Dialog", "背景色:红色2"))
        self.red2.setItemText(0, _translate("Dialog", "黑色"))
        self.red2.setItemText(1, _translate("Dialog", "灰色"))
        self.red2.setItemText(2, _translate("Dialog", "白色"))
        self.label_6.setText(_translate("Dialog", "背景色:橙色"))
        self.orange.setItemText(0, _translate("Dialog", "黑色"))
        self.orange.setItemText(1, _translate("Dialog", "灰色"))
        self.orange.setItemText(2, _translate("Dialog", "白色"))
        self.label_7.setText(_translate("Dialog", "背景色:黄色"))
        self.yellow.setItemText(0, _translate("Dialog", "黑色"))
        self.yellow.setItemText(1, _translate("Dialog", "灰色"))
        self.yellow.setItemText(2, _translate("Dialog", "白色"))
        self.label_8.setText(_translate("Dialog", "背景色:绿色"))
        self.green.setItemText(0, _translate("Dialog", "黑色"))
        self.green.setItemText(1, _translate("Dialog", "灰色"))
        self.green.setItemText(2, _translate("Dialog", "白色"))
        self.label_9.setText(_translate("Dialog", "背景色:青色"))
        self.cyan.setItemText(0, _translate("Dialog", "黑色"))
        self.cyan.setItemText(1, _translate("Dialog", "灰色"))
        self.cyan.setItemText(2, _translate("Dialog", "白色"))
        self.label_10.setText(_translate("Dialog", "背景色:蓝色"))
        self.blue.setItemText(0, _translate("Dialog", "黑色"))
        self.blue.setItemText(1, _translate("Dialog", "灰色"))
        self.blue.setItemText(2, _translate("Dialog", "白色"))
        self.label_11.setText(_translate("Dialog", "背景色:紫色"))
        self.purple.setItemText(0, _translate("Dialog", "黑色"))
        self.purple.setItemText(1, _translate("Dialog", "灰色"))
        self.purple.setItemText(2, _translate("Dialog", "白色"))
        self.saveSettingBtn.setText(_translate("Dialog", "保存设定"))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
